### ISSUE TITLE
C Sharp support?

### ISSUE THREAD

**Issue by funyeatsalad** [magicalnoob/Open-2D-Robeats#2]
Will there ever be support for C hashtag? I know it wil be hard but I am a big thinker! @y3th

**Comment by funyeatsalad** [comment]
![untitled](https://user-images.githubusercontent.com/73189162/98776898-6ece5200-23b5-11eb-8031-986658688b3f.png)

**Comment by funyeatsalad** [comment]
![2chests](https://user-images.githubusercontent.com/73189162/98776929-80aff500-23b5-11eb-9e65-a3df2401b91b.PNG)

**Comment by magicalnoob** [comment]
Working!!!!!!!!!!!!!!
